# es6

## await 捕获错误

- `const [err, data] = await fun()`
